### ISSUE TITLE
a11y: 404 page does not honour prefers-reduced-motion

### ISSUE THREAD

**Issue by xMdb** [Halo-Lab/halo-lab#185]
The 404 page with the moving black hole does not honour the CSS media feature of prefers-reduced-motion.
Details: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by lazio** [comment]
Thank you @xMdb , I'll look into it and let you know

**Comment by lazio** [comment]
Hey @xMdb, finally did it, thanks again for the report
https://github.com/Halo-Lab/halo-lab/pull/186
